### ISSUE TITLE
Add one example to understand scenerios better

### ISSUE THREAD

**Issue by parmeetmaster** [Iteo/cached#65]
Please add one example to understand scenerio of usage better and implement

**Comment by Axot017** [comment]
Hi @parmeetmaster! Thanks for creating this issue.

Could you add more details/describe what is hard to understand in readmy? Because there are a simple use case in documentation in `Motivation` section: https://pub.dev/packages/cached#motivation

**Comment by Axot017** [comment]
I'm closing it due to inactivity. Feel free to reopen if it's needed.

**Comment by mw66** [comment]
@Axot017  I think what @parmeetmaster means is a complete stand-alone example of how to use this package.

E.g. in your https://pub.dev/packages/cached#motivation section:

```
@WithCache()
abstract mixin class RemoteRepository implements Repository, _$RemoteRepository {
...
```

does not match in the following doc:

```
@WithCache()
abstract mixin class Gen implements _$Gen {
  factory Gen() = _Gen;

  ...
}
```

So what exactly is _$Gen ?

A stand-alone runnable example will make this more clear.

Thanks.

**Comment by parmeetmaster** [comment]
_$Gen is a freezed generated class

**Comment by mw66** [comment]
An stand-alone example will make this more clear.
