### ISSUE TITLE
Cache peek

### ISSUE THREAD

**Issue by ryanheise** [Iteo/cached#70]
It would be nice to have a way to peek at a value in the cache. One possible API design is:

```dart
@Cached()
Future<Result> getResult(params...) { ... }

@CachePeek(methodName: 'getResult')
Result? getResultCached(params...);
```

This method returns either the cached result or `null` if no result is cached.

**Comment by Axot017** [comment]
Hi @ryanheise! 
Thanks for creating this issue. For me it sounds great 😄 
We will implement this feature in version 1.3.0

**Comment by Axot017** [comment]
Version 1.3.0 released
