### ISSUE TITLE
Use other cache libraries, e.g. `shared_preferences`, `hive`

### ISSUE THREAD

**Issue by akamoroz** [Iteo/cached#78]
Thank you so much for providing such great package! I'm using it a lot.

However, in some cases I need to store cache in more persistent place than memory, e.g. `shared_preferences` or `hive`.
Also, I think on the second/third/etc application boot using saved cache in `shared_preferences` is better than making call the API during the initialization.

It seems not possible for now using your package. So, do you have any plans or workarounds to support using not only in-memory cache?

**Comment by Axot017** [comment]
@akamoroz We just released version 1.6.0 which has persistent storage feature so I'm closing this issue.
