### ISSUE TITLE
LRU algorithm not implement

### ISSUE THREAD

**Issue by richshaw2015** [Iteo/cached#93]
When set limit to 1 , the second item will never hit the cache! As show in the generated code, the last item will be removed!

```
  @Cached(
    syncWrite: true,
    limit: 1,
  )
```

```
if (_queryCached.length > 1) {
  _queryCached.remove(_queryCached.entries.last.key);
}
```

**Comment by Axot017** [comment]
Hi! Thanks for reporting this bug. We will release hotfix for this soon
